### PR TITLE
404 page (fixes: #361)

### LINKED ISSUE #361: Not found page should be shown when going to non existent route

### PR DESCRIPTION
**Pull request by SujalLama**
Fixes #361 

### Description
404 page added to the app

### Screenshots
mobile view
mob

desktop 
desk

### Links and Curls
src/App.jsx
src/screens/pageNotFound/PageNotFound.jsx
http://localhost:3000/dashboard/asdhf

### CODE REVIEW

**Review by lmmrssa — CHANGES_REQUESTED** [review]
Try to use signout layout as this screen is not looking similar to login page. spacing are off

File: src/screens/pageNotFound/PageNotFound.jsx [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import React from 'react'
+import { useHistory } from 'react-router-dom'
+import SignLayout from '../../layout/signLayout/SignLayout'
+import './PageNotFound.scss'
+
+const PageNotFound = () => {
+  const history = useHistory()
+  return (
+    <SignLayout bannerClass='not-found-page--banner'>
+      <form className='sign'>
```
Comment (lmmrssa) [inline src/screens/pageNotFound/PageNotFound.jsx:10]: form is not required

**Review by lmmrssa — APPROVED** [review]
